spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5656
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
